### ISSUE TITLE
Color issue in Java code

### ISSUE THREAD

**Issue by mustofa-id** [xr0master/vscode-intellij-darcula-theme#3]
Hi, Please fix color in Java code.
![Screenshot_20190324_075732](https://user-images.githubusercontent.com/25121822/54873560-07901280-4e0b-11e9-91a7-2a64fa35775c.png)
Thank you!

**Comment by xr0master** [comment]
The problem that the Webstrom doesn't work with Java, if you can show me how it will in Java, I'll do it.
Or you can create the PR too

**Comment by mustofa-id** [comment]
My bad, I didn't realize that from WebStorm, I thought it was the same as the Intellij Idea, I'm sorry. I think WebStorm uses the same theme as Idea.
