### ISSUE TITLE
Can we give a gray orange theme of webstorm

### ISSUE THREAD

**Issue by jahnli** [xr0master/vscode-intellij-darcula-theme#5]
Can we give a gray orange theme of webstorm

**Comment by xr0master** [comment]
Hey. Thank you for your interest!
Um... I have no idea what is "gray orange theme". Can you explain what do you mean, please?
I think that the Darcula theme is gray/orange theme. Did you check it?

**Comment by jahnli** [comment]
![QQ截图20191029213839](https://user-images.githubusercontent.com/20943608/67772221-a90fce80-fa94-11e9-95d3-4c91a83c005b.png)
Something like this

**Comment by jahnli** [comment]
[grey_orange.zip](https://github.com/xr0master/vscode-intellij-darcula-theme/files/3783784/grey_orange.zip)
This is a websotrm theme package and I would like to ask if you can convert it

**Comment by xr0master** [comment]
Hey. Unfortunately, I don’t have a “script” to convert anything. This is a manual, tedious process.
